config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :users, only: :show
  
  resources :events do
    resources :invitations, controller: :event_invitations, except: %i[ show edit update ]
    resources :attendees, only: %i[ index create ]
    delete :attendees, to: 'attendees#destroy'
  end

  get 'user/invitations', to: 'users#invitations', as: :user_invitations
  get 'search/', to: 'search#show', as: :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  scope :upcoming, -> { where("start_date > ?", Time.now.utc) }
  scope :previous, -> { where("start_date < ?", Time.now.utc) }

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, :location, :start_date, :end_date, presence: true
  validates :private, comparison: { greater_than: -1, less_than: 2 }

  validate :validate_event_dates

  belongs_to :host,
    class_name: 'User',
    foreign_key: :user_id

  has_many :event_visitors
  has_many :attendees,
    through: :event_visitors,
    source: :user,
    dependent: :destroy

  has_many :event_invitations
  has_many :invited_users,
    through: :event_invitations,
    source: :user,
    dependent: :destroy

  def in_the_past?
    start_date < Time.now.utc ? true : false
  end

  def private?
    private == 1
  end

  private

  def validate_event_dates
    if start_date && start_date < Time.zone.now
      errors.add(:start_date, "can't be in the past")
    end

    if start_date && end_date && end_date <= start_date
      errors.add(:end_date, "can't be before the starting date")
    end
  end
end

app/models/event_invitation.rb
class EventInvitation < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event_visitor.rb
class EventVisitor < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true, length: { maximum: 40 }

  has_many :events,
    dependent: :destroy
     
  has_many :event_visitors
  has_many :visits, 
    through: :event_visitors, 
    source: :event, 
    dependent: :destroy
  
  has_many :invitations, 
    class_name: 'EventInvitation', 
    inverse_of: :user,
    dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_event
  before_action :authenticate_user!, except: %i[ index ]

  def index
  end

  def create
    if @event.attendees.include?(current_user)
      notice = 'You are already registered for this event.'
    else
      @event.attendees << current_user
      notice = 'You successfully registered for this event.'
    end
    redirect_to @event, notice: notice
  end

  def destroy
    @event.attendees.destroy(current_user)
    redirect_to @event, alert: 'You successfully unregistered from this event.'
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/event_invitations_controller.rb
class EventInvitationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event

  def index
    @invited_users = @event.invited_users
  end
  
  def new
    @invitation = @event.event_invitations.new
  end

  def create
    @invitation = @event.event_invitations.new
    @user = find_user(params[:event_invitation][:name_or_email])
    @invitation.user = @user
    
    if @invitation.valid? && user_inviteable?
      @invitation.save
      redirect_to new_event_invitation_path, notice: "#{@user.username} has been invited."
    else
      flash.now[:alert] = "User was not invited."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @invitation = EventInvitation.find(params[:id])
    if params[:commit] == 'Accept'
      @invitation.event.attendees << @invitation.user
      notice = 'You have accepted the invitation.'
    else
      notice = 'You have rejected the invitation.'
    end
    @invitation.destroy
    path = params[:commit] == 'Revoke Invitation' ? event_invitations_path(@event) : user_invitations_path(@invitation.user)
    redirect_to path, notice: notice
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def find_user(name_or_email)
    User.find_by('email = :s OR username = :s', { s: name_or_email })
  end

  def user_inviteable?
    @event.host != @user &&
      %i[ attendees invited_users ].none? { |m| @event.send(m).include?(@user) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, except: %i[ index new create ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :restrict_access_to_host, only: %i[ edit update destroy ]

  def index
    @upcoming_events = Event.upcoming.includes(:host, :attendees).order('start_date')
    @past_events     = Event.previous.includes(:host, :attendees).order('start_date')
  end

  def show
  end

  def edit
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event has been successfully created.'
    else
      flash.now[:alert] = 'Event has not been created.'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event has been successfully updated.'
    else
      flash.now[:alert] = 'Event has not been updated.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, alert: 'Event has been destroyed.'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :start_date, :end_date, :private)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def restrict_access_to_host
    (redirect_to @event, notice: 'You are not allowed to view this page.') if @event.host != current_user
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    @search_term = params[:s]
    @events = Event.where('LOWER(name) LIKE :s OR LOWER(location) LIKE :s OR LOWER(description) LIKE :s', { s: "%#{@search_term.downcase}%" })
    @users  = User.where('LOWER(username) LIKE ?', "%#{@search_term.downcase}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :invitations

  def show
    @user = User.find(params[:id])
  end

  def invitations
    @invitations = current_user.invitations.includes(:event)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/event_invitations_helper.rb
module EventInvitationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendees/_form.html.erb
<%= form_with url: event_attendees_path(event), html: { method: event.attendees.include?(current_user) ? :delete : :post }, data: { turbo_method: false }, class: 'event-registration' do |f| %>
  <%= f.submit (event.attendees.include?(current_user) ? 'Unregister' : 'Register') %>
<% end %>

app/views/attendees/index.html.erb
<h2 class="heading bold">Attendees for <%= @event.name %></h2>

<ul class="flex column gap-10">
  <% @event.attendees.each do |attendee| %>
    <li class="flex gap-10">
      <%= link_to(user_path(attendee), class: 'flex gap-10 align-center') do %>
        <%= image_tag "https://source.unsplash.com/random/30x30?v=#{attendee.id}", size: '30x30', style: 'border-radius: 50%;' %>
        <span class="bold small"><%= attendee.username %></span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/event_invitations/index.html.erb
<h2 class="heading bold">Pending invitations for <%= @event.name %></h2>

<ul class="flex column gap-20">
  <% @event.invited_users.each do |user| %>
    <li class="flex gap-10 align-center">
      <%= link_to user.username, user, class: 'bold' %>
      <%= form_with url: event_invitation_path(@event, EventInvitation.find_by(user_id: user.id, event_id: @event.id)), html: { method: :delete }, data: { turbo: false } do |f| %>
        <div class="actions">
          <%= f.submit 'Revoke Invitation', class: 'revoke-invitation-btn' %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'Invite user', new_event_invitation_path(@event), class: 'small bold' %>

app/views/event_invitations/new.html.erb
<h2 class="heading bold align-self-center">Invite users for <%= @event.name %></h2>

<%= form_with model: @invitation do |f| %>
  <div class="field">
    <%= f.label :name_or_email, 'Username or email address' %>
    <%= f.text_field :name_or_email, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit 'Invite' %>
  </div>
<% end %>

<%= link_to 'Show invited users', event_invitations_path(@event), class: 'small bold align-self-center' %>

app/views/events/_event.html.erb
<div class="event flex column gap-10">
  <%= link_to event do %>
    <%= image_tag "https://source.unsplash.com/random/400x120?v=#{event.id}", width: '400px', height: '120px' %>
  <% end %>

  <div class="flex column gap-10 pad-10">
    <p><%= link_to event.name, event, class: 'bold' %><p>
    
    <div class="flex gap-5">
      <svg style="width:18px;height:18px" viewBox="0 0 24 24">
        <path fill="currentColor" d="M9,10H7V12H9V10M13,10H11V12H13V10M17,10H15V12H17V10M19,3H18V1H16V3H8V1H6V3H5C3.89,3 3,3.9 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3M19,19H5V8H19V19Z" />
      </svg>
      <p class="event-date very-small"><%= event.start_date.strftime('%a, %b %e %R, %Y') %></p>
    </div>

    <div class="flex gap-5">
      <svg style="width:18px;height:18px" viewBox="0 0 24 24">
        <path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" />
      </svg>
      <p class="event-location very-small"><%= event.location %></p>
    </div>

    <div class="flex gap-5">
      <svg style="width:18px;height:18px" viewBox="0 0 24 24">
        <path fill="currentColor" d="M12,19.2C9.5,19.2 7.29,17.92 6,16C6.03,14 10,12.9 12,12.9C14,12.9 17.97,14 18,16C16.71,17.92 14.5,19.2 12,19.2M12,5A3,3 0 0,1 15,8A3,3 0 0,1 12,11A3,3 0 0,1 9,8A3,3 0 0,1 12,5M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12C22,6.47 17.5,2 12,2Z" />
      </svg>
      <%= link_to event.host.username, user_path(event.host), class: 'event-author very-small bold' %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with model: event do |f| %>
  <div class="field">
    <%= f.label :name do %>
      Name
      <em class="small">(100 characters maximum)</em>
    <% end %>
    <%= f.text_field :name, autofocus: true, maxLength: 100 %>
    <%= render 'public/error_field', resource: event, attribute: :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: '5' %>
    <%= render 'public/error_field', resource: event, attribute: :description %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= render 'public/error_field', resource: event, attribute: :location %>
  </div>

  <% if event.new_record? || !event.in_the_past? %>
    <div class="field">
      <%= f.label :start_date %>
      <%= f.datetime_field :start_date %>
      <%= render 'public/error_field', resource: event, attribute: :start_date %>
      <i class="small">(Date values are in UTC format)</i>
    </div>

    <div class="field">
      <%= f.label :end_date %>
      <%= f.datetime_field :end_date %>
      <%= render 'public/error_field', resource: event, attribute: :end_date %>
    </div>
  <% end %>

  <div class="field flex gap-5 align-center">
    <%= f.check_box :private %>
    <%= f.label :private %>
  </div>

  <div class="actions align-self-center">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/attendees.html.erb
<h2 class="heading bold">Attendees for <%= @event.name %></h2>

<ul class="flex column gap-10">
  <% @event.attendees.each do |attendee| %>
    <li class="flex gap-10">
      <%= link_to(user_path(attendee), class: 'flex gap-10 align-center') do %>
        <%= image_tag "https://source.unsplash.com/random/30x30?v=#{attendee.id}", size: '30x30', style: 'border-radius: 50%;' %>
        <span class="bold small"><%= attendee.username %></span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/events/edit.html.erb
<h2 class="heading bold align-self-center">Edit Event</h2>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h2 class="heading bold">Upcoming Events</h2>

<div class="events">
  <%= render @upcoming_events %>
</div>

<% if @past_events.any? %>
  <h2 class="heading bold">Past Events</h2>

  <div class="events previous-events flex gap-20">
    <%= render @past_events %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1 class="heading bold align-self-center">Create Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= image_tag 'https://source.unsplash.com/random/600x300?v=1', class: 'event-listing-bg-img', width: '98%', height: '55%' %>

<div class="event-listing flex column align-self-center">
  <div class="event-header">
    <%= image_tag 'https://source.unsplash.com/random/600x300?v=1', size: '600x300' %>

    <div class="pad-10 flex column gap-10 justify-between">
      <div class="flex justify-between">
        <p class="small bold"><%= @event.start_date.strftime('%d %b') %></p>

        <% if user_signed_in? && current_user == @event.host %>
          <div class="flex gap-5">
            <% if @event.private? %>
              <%= link_to event_invitations_path(@event) do %>
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                  <path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z" />
                </svg>
              <% end %>
            <% end %>

            <%= link_to new_event_invitation_path(@event) do %>
              <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path fill="currentColor" d="M19 17V19H7V17S7 13 13 13 19 17 19 17M16 8A3 3 0 1 0 13 11A3 3 0 0 0 16 8M19.2 13.06A5.6 5.6 0 0 1 21 17V19H24V17S24 13.55 19.2 13.06M18 5A2.91 2.91 0 0 0 17.11 5.14A5 5 0 0 1 17.11 10.86A2.91 2.91 0 0 0 18 11A3 3 0 0 0 18 5M8 10H5V7H3V10H0V12H3V15H5V12H8Z" />
              </svg>
            <% end %>

            <%= link_to edit_event_path(@event) do %>
              <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path fill="currentColor" d="M12,15.5A3.5,3.5 0 0,1 8.5,12A3.5,3.5 0 0,1 12,8.5A3.5,3.5 0 0,1 15.5,12A3.5,3.5 0 0,1 12,15.5M19.43,12.97C19.47,12.65 19.5,12.33 19.5,12C19.5,11.67 19.47,11.34 19.43,11L21.54,9.37C21.73,9.22 21.78,8.95 21.66,8.73L19.66,5.27C19.54,5.05 19.27,4.96 19.05,5.05L16.56,6.05C16.04,5.66 15.5,5.32 14.87,5.07L14.5,2.42C14.46,2.18 14.25,2 14,2H10C9.75,2 9.54,2.18 9.5,2.42L9.13,5.07C8.5,5.32 7.96,5.66 7.44,6.05L4.95,5.05C4.73,4.96 4.46,5.05 4.34,5.27L2.34,8.73C2.21,8.95 2.27,9.22 2.46,9.37L4.57,11C4.53,11.34 4.5,11.67 4.5,12C4.5,12.33 4.53,12.65 4.57,12.97L2.46,14.63C2.27,14.78 2.21,15.05 2.34,15.27L4.34,18.73C4.46,18.95 4.73,19.03 4.95,18.95L7.44,17.94C7.96,18.34 8.5,18.68 9.13,18.93L9.5,21.58C9.54,21.82 9.75,22 10,22H14C14.25,22 14.46,21.82 14.5,21.58L14.87,18.93C15.5,18.67 16.04,18.34 16.56,17.94L19.05,18.95C19.27,19.03 19.54,18.95 19.66,18.73L21.66,15.27C21.78,15.05 21.73,14.78 21.54,14.63L19.43,12.97Z" />
              </svg>
            <% end %>

            <%= button_to @event, method: :delete, data: { turbo: false } do %>
              <svg style="width:24px;height:24px;" viewBox="0 0 24 24">
                <path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" />
              </svg>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="flex column gap-10">
        <h1 class="heading bold"><%= @event.name %></h1>
        <p class="small">hosted by <%= link_to @event.host.username, user_path(@event.host), class: 'bold' %></p>
      </div>

      <div>
        <% if user_signed_in? && current_user != @event.host && !@event.in_the_past? && !@event.private? %>
          <%= render 'attendees/form', event: @event %>
        <% end %>

        <% if @event.private? %>
          <span class="event-notice bold">Private Event</span>
        <% end %>

        <% if @event.in_the_past? %>
          <span class="event-notice bold">Event registration is closed.</span>
        <% end %>
      </div>
    </div>
  </div>

  <% if @event.attendees.any? %>
    <div class="event-attendees flex gap-10 align-center">
      <% @event.attendees.limit(5).each do |attendee| %>
        <%= link_to(user_path(attendee), class: 'align-self-start') do %>
          <%= image_tag "https://source.unsplash.com/random/30x30?v=#{attendee.id}", size: '30x30', style: 'border-radius: 50%;' %>
        <% end %>
      <% end %>

      <p>
        <% if @event.attendees.size > 5 %>
          <%= link_to "+#{@event.attendees.size - 5} more users", event_attendees_path(@event) %>
        <% end %>
        are attending this event.
      </p>
    </div>
  <% end %>

  <div class="event-details flex justify-between">
    <div class="event-description flex column gap-10">
      <h3 class="bold">Description</h3>
      <p class="small"><%= @event.description %></p>
    </div>
    
    <aside class="flex column gap-40">
      <div class="flex gap-10">
        <svg style="width:24px;height:24px" viewBox="0 0 24 24">
          <path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" />
        </svg>

        <div class="location flex column gap-10">
          <h3 class="bold">Location</h3>
          <p class="small"><%= @event.location %></p>
        </div>
      </div>

      <div class="flex gap-10">
        <svg style="width:24px;height:24px" viewBox="0 0 24 24">
          <path fill="currentColor" d="M9,10H7V12H9V10M13,10H11V12H13V10M17,10H15V12H17V10M19,3H18V1H16V3H8V1H6V3H5C3.89,3 3,3.9 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3M19,19H5V8H19V19Z" />
        </svg>

        <div class="date flex column gap-10">
          <h3 class="bold">Date</h3>
          <p class="small">
            <% if @event.start_date.beginning_of_day == @event.end_date.beginning_of_day %>
             <%= @event.start_date.strftime('%a %b %e %Y %H:%M - ') %><%= @event.end_date.strftime('%H:%M UTC') %>
            <% else %>
              <%= @event.start_date.ctime %> -</br > <%= @event.end_date.ctime %> UTC
            <% end %>
          </p>
        </div>
      </div>
    </aside>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="header flex gap-20 align-center justify-between">
  <%= link_to root_path, class: 'main-heading' do %>
    Private<span>Events</span>
  <% end %>

  <%= render 'search/form' %>

  <nav class="navigation flex">
    <ul class="flex gap-20 align-center">
      <li><%= link_to 'Create Event', new_event_path, class: 'bold' %></li>

      <% if user_signed_in? %>
        <% if current_user.invitations.any? %>
          <li>
            <%= link_to user_invitations_path do %>
              <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path fill="currentColor" d="M13,13H11V7H13M13,17H11V15H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" />
              </svg>
            <% end %>
          </li>
        <% end %>

        <li>
          <%= link_to user_path(current_user) do %>
            <svg style="width:26px;height:26px" viewBox="0 0 24 24">
              <path fill="currentColor" d="M12,3L2,12H5V20H19V12H22L12,3M12,8.75A2.25,2.25 0 0,1 14.25,11A2.25,2.25 0 0,1 12,13.25A2.25,2.25 0 0,1 9.75,11A2.25,2.25 0 0,1 12,8.75M12,15C13.5,15 16.5,15.75 16.5,17.25V18H7.5V17.25C7.5,15.75 10.5,15 12,15Z" />
            </svg>
          <% end %>
        </li>

        <li>
          <%= link_to edit_user_registration_path do %>
            <svg style="width:26px;height:26px" viewBox="0 0 24 24">
              <path fill="currentColor" d="M21.7,13.35L20.7,14.35L18.65,12.3L19.65,11.3C19.86,11.09 20.21,11.09 20.42,11.3L21.7,12.58C21.91,12.79 21.91,13.14 21.7,13.35M12,18.94L18.06,12.88L20.11,14.93L14.06,21H12V18.94M12,14C7.58,14 4,15.79 4,18V20H10V18.11L14,14.11C13.34,14.03 12.67,14 12,14M12,4A4,4 0 0,0 8,8A4,4 0 0,0 12,12A4,4 0 0,0 16,8A4,4 0 0,0 12,4Z" />
            </svg>
          <% end %>
        </li>

        <li>
          <%= button_to destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'flex align-center' do %>
            <svg style="width:26px;height:26px;color:#6e0710" viewBox="0 0 24 24">
              <path fill="currentColor" d="M16,17V14H9V10H16V7L21,12L16,17M14,2A2,2 0 0,1 16,4V6H14V4H5V20H14V18H16V20A2,2 0 0,1 14,22H5A2,2 0 0,1 3,20V4A2,2 0 0,1 5,2H14Z" style="color:#960f0f;"/>
            </svg>
          <% end %>
        </li>
      <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path, class: 'bold' %></li>
        <li><%= link_to 'Log In', new_user_session_path, class: 'bold' %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex column">
    <%= render 'layouts/header' %>

    <main class="pad-20 flex column gap-20">
      <% if flash.any? %>
        <div class="flash-messages pad-10 align-self-center">
          <% flash.each do |type, msg| %>
            <% if %w[ alert notice ].include?(type) %>
              <p class="<%= type %>"><%= msg %></p>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/search/_form.html.erb
<%= form_with(url: search_path, method: :get, class: 'search-form') do |f| %>
  <div class="search">
    <%= f.text_field :s, placeholder: 'Search' %>
  </div>
<% end %>

app/views/search/show.html.erb
<h2 class="heading bold">Results for '<%= @search_term %>'</h2>

<h3 class="bold">Event matches</h3>
<div class="events">
  <% if @events.any? %>
    <% @events.each do |event| %>
      <%= render 'events/event', event: event %>
    <% end %>
  <% else %>
    <em class="small">no matches</em>
  <% end %>
</div>

<h3 class="bold">User matches</h3>
<div class="flex column gap-10">
  <% if @users.any? %>
    <% @users.each do |user| %>
      <div>
        <%= link_to user, class: 'flex gap-10 align-center' do %>
          <%= image_tag "https://source.unsplash.com/random/30x30?v=#{user.id}", size: '30x30', style: 'border-radius: 50%;' %>
          <span><%= user.username %></span>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <em class="small">no matches</em>
  <% end %>
</div>

app/views/users/invitations.html.erb
<h2 class="heading bold">You have been invited to the following events</h2>

<div class="events">
  <% @invitations.each do |invitation| %>
    <div class="flex column gap-10">
      <%= render 'events/event', event: invitation.event %>

      <%= form_with url: event_invitation_path(invitation.event, invitation), html: { method: :delete }, data: { turbo: false } do |f| %>
        <div class="actions flex gap-10 align-self-center">
          <%= f.submit 'Accept' %>
          <%= f.submit 'Decline' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-card pad-10 flex column gap-10 align-center align-self-center">
  <%= image_tag "https://source.unsplash.com/random/100x100?v=#{@user.id}", size: '100x100', style: 'border-radius: 50%;border:1px solid white;' %>
  <h2 class="heading bold"><%= @user.username %></h2>
</div>

<h3 class="heading bold">Hosted Events (<%= @user.events.size %>)</h3>

<span class="bold">Upcoming Events</span>
<div class="events">
  <%= render @user.events.upcoming %>
</div>

<span class="bold">Past Events</span>
<div class="events">
  <%= render @user.events.previous %>
</div class="events">

<h3 class="heading bold">Visited Events (<%= @user.visits.size %>)</h3>
<div class="events">
  <% @user.visits.each do |event| %>
    <%= render 'events/event', event: event %>
  <% end %>
</div>